Algoritmo "ESTRUTURA_DE_REPETICAO"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Tiago Silva - YouTube
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Wallace Duarte
// Data atual  : 15/08/2026
Var
   i, tabuada, resultado: inteiro
   
Inicio
      escreva("Escolha um numero para a Tabuada: ")
      leia(tabuada)
      
      para i de 1 ate 10 faca
           resultado <- (tabuada * i)
           escreval(tabuada, " x",i, " =",(tabuada * i))
      fimpara


Fimalgoritmo