Algoritmo "REPITA_MAIS"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Tiago Silva - YouTube
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Wallace Duarte
// Data atual  : 15/08/2026
Var
   repita_mais: caracter


Inicio
   escreval(" Repetir até 'n' ser digitado.")
   escreval("------------------------------")
   repita
      escreval("Repetir mais uma vez? s/n")
      leia(repita_mais)
   ate(repita_mais = "n")

   escreval("Fim da repetição.")


Fimalgoritmo